accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name="accounts/logout.html"), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("photo.urls")),
    path('accounts/', include('accounts.urls')),
]

instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

photo/urls.py
from django.urls import path
from .views import PhotoCreate, PhotoDelete, PhotoDetail, PhotoList, PhotoUpdate

app_name = "photo"
urlpatterns = [
    path("delete/<int:pk>/", PhotoDelete.as_view(), name='delete'),
    path("create/", PhotoCreate.as_view(), name='create'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name='detail'),
    path("", PhotoList.as_view(), name='index'),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to= 'timeline_photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "text : "+self.text

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse("photo:detail", args=[self.id])
    

accounts/views.py
from django.shortcuts import render

# Create your views here.

photo/views.py
from django.http import request
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Photo
from django.contrib import messages
from django.http import HttpResponseRedirect

# Create your views here.
def test(request): #test용
    return render(request, "base.html")

class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'
    
class PhotoCreate(CreateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_create'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form':form})

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_update'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, "수정할 권한이 없습니다.")
            return HttpResponseRedirect('/')
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)


class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, "삭제할 권한이 없습니다.")
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'
    

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<!-- static 연결 -->
<link rel="stylesheet" href="{% static "login.css" %}">
{% endblock %}

{% block content %}
<!-- html 내용 작성 -->
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="login">
    </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<!-- static 연결 -->
<link rel="stylesheet" href="{% static "login.css" %}">
{% endblock %}

{% block content %}
<!-- html 내용 작성 -->
    <div class="alert" role= alert>로그아웃 되었습니다.</div>
    <a href="{% url 'accounts:login' %}" >로그인하기</a>
{% endblock %}

photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<!-- static 연결 -->
<link rel="stylesheet" href="{% static "photo_list.css" %}">
{% endblock %}
{% block content %}
<!-- html 내용 작성 -->
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {{form.as_p}}
    <input type="submit" value="Upload" class="btn">
</form>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<!-- static 연결 -->
<link rel="stylesheet" href="{% static "photo_list.css" %}">
{% endblock %}
{% block content %}
<!-- html 내용 작성 -->
    <div class="alert" role="alert">정말 {{object}}를 삭제하시겠습니까?</div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete OK">
    </form>
{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
<!-- static 연결 -->
<link rel="stylesheet" href="{% static "photo_list.css" %}">
{% endblock %}
{% block content %}
<!-- html 내용 작성 -->
    <form action="" method="POST">
        {% csrf_token %}

        {{form.as_p}}
        <input type="submit" value="Create" class="btn">
    </form>
{% endblock %}